# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamesdk_login.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gamesdk_login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gamesdk_login.proto\"\xe6\x01\n\x0fGameAccountsDto\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1a\n\x08user_dto\x18\x0b \x01(\x0b\x32\x08.UserDto\x12&\n\rgame_accounts\x18\x0c \x03(\x0b\x32\x0f.GameAccountDto\x12\x0f\n\x07\x63hannel\x18\r \x01(\x05\x12\r\n\x05\x61\x64_id\x18\x0e \x01(\t\x12\x0e\n\x06ticket\x18\x0f \x01(\t\x12\x1a\n\x12\x61\x63\x63ount_sharing_id\x18\x11 \x01(\t\x12\x16\n\x0eserver_country\x18\x12 \x01(\t\x12\x10\n\x08trace_id\x18\x13 \x01(\t\"\xcf\x01\n\x07UserDto\x12\x0f\n\x07user_id\x18\x0b \x01(\t\x12\x11\n\tuser_name\x18\x0c \x01(\t\x12\r\n\x05\x65mail\x18\r \x01(\t\x12\x0e\n\x06mobile\x18\x0e \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x0f \x01(\t\x12\x13\n\x0buser_status\x18\x10 \x01(\t\x12\x18\n\x10real_name_status\x18\x11 \x01(\t\x12\x0b\n\x03\x61ge\x18\x12 \x01(\x05\x12\x1c\n\x14twice_real_name_auth\x18\x13 \x01(\x08\x12\x12\n\nclass_name\x18\x7f \x01(\t\"\xfc\x02\n\x0eGameAccountDto\x12\n\n\x02id\x18\x0b \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x0c \x01(\t\x12\x0f\n\x07user_id\x18\r \x01(\t\x12\x11\n\tdevice_id\x18\x0e \x01(\t\x12\r\n\x05model\x18\x0f \x01(\t\x12\x0e\n\x06status\x18\x10 \x01(\x05\x12\x10\n\x08pkg_name\x18\x11 \x01(\t\x12\x1c\n\x14\x61\x63\x63ount_is_protected\x18\x12 \x01(\t\x12\x16\n\x0eprotected_days\x18\x13 \x01(\x05\x12\x13\n\x0btrade_limit\x18\x14 \x01(\t\x12\x15\n\ruser_tag_type\x18\x15 \x01(\t\x12\x1b\n\x13\x61\x63\x63ount_sharing_tag\x18\x16 \x01(\x05\x12\x1a\n\x12\x61\x63\x63ount_sharing_id\x18\x17 \x01(\t\x12\x16\n\x0eneed_face_scan\x18\x18 \x01(\x08\x12\x16\n\x0eneed_login_pop\x18\x19 \x01(\x08\x12\x14\n\x0c\x66irst_create\x18\x1a \x01(\x08\x12\x12\n\nclass_name\x18\x7f \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamesdk_login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEACCOUNTSDTO']._serialized_start=24
  _globals['_GAMEACCOUNTSDTO']._serialized_end=254
  _globals['_USERDTO']._serialized_start=257
  _globals['_USERDTO']._serialized_end=464
  _globals['_GAMEACCOUNTDTO']._serialized_start=467
  _globals['_GAMEACCOUNTDTO']._serialized_end=847
# @@protoc_insertion_point(module_scope)
