# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamesdk_latest_role.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gamesdk_latest_role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19gamesdk_latest_role.proto\"\xab\x02\n\x11GameAccountMsgDto\x12\x0e\n\x06userId\x18\x0b \x01(\t\x12\x11\n\taccountId\x18\x0c \x01(\t\x12\x0f\n\x07realmId\x18\r \x01(\t\x12\x11\n\trealmName\x18\x0e \x01(\t\x12\x0e\n\x06roleId\x18\x0f \x01(\t\x12\x10\n\x08roleName\x18\x10 \x01(\t\x12\x11\n\tloginTime\x18\x11 \x01(\x03\x12\x11\n\troleLevel\x18\x12 \x01(\x05\x12\x13\n\x0b\x61\x63\x63ountName\x18\x13 \x01(\t\x12\x19\n\x11\x61\x63\x63ountSharingTag\x18\x14 \x01(\x05\x12\x18\n\x10\x61\x63\x63ountSharingId\x18\x15 \x01(\t\x12\x14\n\x0cneedFaceScan\x18\x16 \x01(\x08\x12\x14\n\x0cneedLoginPop\x18\x17 \x01(\x08\x12\x11\n\tclassName\x18\x7f \x01(\t\"a\n\x15LatestGameAccountsDto\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12-\n\x11\x61\x63\x63ountMsgDtoList\x18\x0b \x03(\x0b\x32\x12.GameAccountMsgDtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamesdk_latest_role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEACCOUNTMSGDTO']._serialized_start=30
  _globals['_GAMEACCOUNTMSGDTO']._serialized_end=329
  _globals['_LATESTGAMEACCOUNTSDTO']._serialized_start=331
  _globals['_LATESTGAMEACCOUNTSDTO']._serialized_end=428
# @@protoc_insertion_point(module_scope)
