# coding=UTF-8
"""
Copyright (c) 2026 KKeygen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

import asyncio
import os
import shutil
import sys
import threading

from envmgr import genv
from logutil import setup_logger


logger = setup_logger()

# Default proxy listen port
DEFAULT_PROXY_PORT = 8899


class MitmProxyManager:
    """Manages mitmproxy running in normal (regular) proxy mode.

    Replaces the old ``proxymgr`` / ``macProxyMgr`` which listened on
    port 443 and required hosts-file manipulation.  The new approach
    sets ``HTTP_PROXY`` / ``HTTPS_PROXY`` environment variables for the
    game subprocess so that all game traffic flows through mitmproxy.
    """

    def __init__(self, *, addon, port=DEFAULT_PROXY_PORT):
        self.addon = addon
        self.port = port
        self._thread: threading.Thread | None = None
        self._master = None
        self._loop: asyncio.AbstractEventLoop | None = None

    # ------------------------------------------------------------------
    # Certificate helpers
    # ------------------------------------------------------------------

    @staticmethod
    def get_confdir() -> str:
        """Return the mitmproxy config directory used for certs."""
        return os.path.join(genv.get("FP_WORKDIR", ""), "mitmproxy-conf")

    def ensure_certificates(self) -> bool:
        """Make sure mitmproxy CA certificates exist and are installed
        in the system trust store.

        If our own CA cert (generated by ``certmgr``) already exists we
        convert it into the format mitmproxy expects and reuse it.
        Otherwise we let mitmproxy generate a fresh CA on first run.

        Returns ``True`` when the CA is ready.
        """
        confdir = self.get_confdir()
        os.makedirs(confdir, exist_ok=True)

        mitm_ca_pem = os.path.join(confdir, "mitmproxy-ca.pem")
        mitm_ca_cert_pem = os.path.join(confdir, "mitmproxy-ca-cert.pem")

        # If mitmproxy certs already exist, just ensure they're installed.
        if os.path.exists(mitm_ca_pem) and os.path.exists(mitm_ca_cert_pem):
            return self._install_ca_cert(mitm_ca_cert_pem)

        # Try to reuse the existing CA generated by certmgr.
        ca_cert_path = genv.get("FP_CACERT", "")
        ca_key_path = genv.get("FP_WEBKEY", "")  # CA key may be stored separately

        # If the app already has a CA key stored for mitmproxy use, read it.
        ca_key_for_mitm = os.path.join(genv.get("FP_WORKDIR", ""), "root_ca_key.pem")

        if ca_cert_path and os.path.exists(ca_cert_path) and os.path.exists(ca_key_for_mitm):
            try:
                with open(ca_key_for_mitm, "rb") as f:
                    key_data = f.read()
                with open(ca_cert_path, "rb") as f:
                    cert_data = f.read()

                # mitmproxy-ca.pem = key + cert
                with open(mitm_ca_pem, "wb") as f:
                    f.write(key_data)
                    if not key_data.endswith(b"\n"):
                        f.write(b"\n")
                    f.write(cert_data)

                # mitmproxy-ca-cert.pem = cert only
                shutil.copy2(ca_cert_path, mitm_ca_cert_pem)

                logger.info("已从现有CA证书生成mitmproxy证书")
                return self._install_ca_cert(mitm_ca_cert_pem)
            except Exception as e:
                logger.warning(f"复用现有CA证书失败，将生成新证书: {e}")

        # Generate fresh CA via certmgr and store in mitmproxy format.
        try:
            from certmgr import certmgr
            cm = certmgr()
            ca_key = cm.generate_private_key(bits=2048)
            ca_cert = cm.generate_ca(ca_key)

            # Export in PEM format
            from cryptography.hazmat.primitives import serialization

            key_pem = ca_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption(),
            )
            cert_pem = ca_cert.public_bytes(serialization.Encoding.PEM)

            with open(mitm_ca_pem, "wb") as f:
                f.write(key_pem + cert_pem)
            with open(mitm_ca_cert_pem, "wb") as f:
                f.write(cert_pem)

            # Also save in the main cert location so the rest of the
            # tool can use it (e.g. for cert installation prompts).
            if ca_cert_path:
                cm.export_cert(ca_cert_path, ca_cert)
            # Save the key for future reuse
            with open(ca_key_for_mitm, "wb") as f:
                f.write(key_pem)

            # Generate server cert for localhost (still useful for some
            # internal flows).
            srv_key = cm.generate_private_key(bits=2048)
            domains = [
                genv.get("DOMAIN_TARGET", "service.mkey.163.com"),
                genv.get("DOMAIN_TARGET_OVERSEA", "sdk-os.mpsdk.easebar.com"),
                "localhost",
            ]
            srv_cert = cm.generate_cert(domains, srv_key, ca_cert, ca_key)
            web_cert_path = genv.get("FP_WEBCERT", "")
            web_key_path = genv.get("FP_WEBKEY", "")
            if web_cert_path:
                cm.export_cert(web_cert_path, srv_cert)
            if web_key_path:
                cm.export_key(web_key_path, srv_key)

            # Install the CA cert
            if ca_cert_path and cm.import_to_root(ca_cert_path) is False:
                logger.error("导入CA证书失败!")
                return False

            logger.info("mitmproxy证书生成并安装成功")
            return True
        except Exception as e:
            logger.exception(f"生成mitmproxy证书失败: {e}")
            return False

    def _install_ca_cert(self, cert_path: str) -> bool:
        """Install the CA certificate into the system trust store."""
        if sys.platform == "win32":
            try:
                from cert_utils import (
                    is_certificate_installed_in_store,
                    install_certificate_to_store,
                )

                if is_certificate_installed_in_store(
                    ["Netease Login Helper CA", "mitmproxy"],
                    cert_path,
                    store_name="ROOT",
                ):
                    return True
                return install_certificate_to_store(cert_path, "ROOT")
            except Exception as e:
                logger.warning(f"安装CA证书失败: {e}")
                return False
        elif sys.platform == "darwin":
            try:
                from certmgr import certmgr
                cm = certmgr()
                return cm.import_to_root(cert_path) is not False
            except Exception as e:
                logger.warning(f"安装CA证书失败 (macOS): {e}")
                return False
        else:
            # Linux: trust store varies by distro; best-effort
            logger.info("Linux平台请手动安装CA证书到系统信任存储")
            return True

    # ------------------------------------------------------------------
    # Proxy lifecycle
    # ------------------------------------------------------------------

    def start(self):
        """Start mitmproxy in a daemon thread."""
        if self._thread and self._thread.is_alive():
            logger.warning("mitmproxy 已经在运行中")
            return

        self._thread = threading.Thread(
            target=self._run_proxy,
            name="mitmproxy-worker",
            daemon=True,
        )
        self._thread.start()
        logger.info(f"mitmproxy 代理已启动，监听端口 {self.port}")

    def _run_proxy(self):
        """Thread target: create an asyncio event loop and run mitmproxy."""
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)

        try:
            from mitmproxy.options import Options
            from mitmproxy.tools.dump import DumpMaster

            confdir = self.get_confdir()
            opts = Options(
                listen_host="127.0.0.1",
                listen_port=self.port,
                confdir=confdir,
                ssl_insecure=True,  # don't verify upstream certs
            )
            self._master = DumpMaster(opts)
            self._master.addons.add(self.addon)
            self._loop.run_until_complete(self._master.run())
        except Exception as e:
            logger.exception(f"mitmproxy 运行出错: {e}")
        finally:
            self._loop.close()

    def stop(self):
        """Shut down the mitmproxy proxy."""
        if self._master:
            try:
                self._master.shutdown()
            except Exception:
                pass

    # ------------------------------------------------------------------
    # Game launching
    # ------------------------------------------------------------------

    def get_proxy_env(self) -> dict:
        """Return a copy of ``os.environ`` with proxy variables set."""
        env = os.environ.copy()
        proxy_url = f"http://127.0.0.1:{self.port}"
        env["HTTP_PROXY"] = proxy_url
        env["HTTPS_PROXY"] = proxy_url
        env["http_proxy"] = proxy_url
        env["https_proxy"] = proxy_url
        return env
