name: Build Beta version

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller -F src/main.py -n idv-login-v10beta-${{github.ref_name}}.exe -i assets/icon.ico --version-file assets/version.txt --uac-admin

      - name: Calcaulate checksum
        run: Get-FileHash "dist/idv-login-v10beta-${{github.ref_name}}.exe" | select-object -ExpandProperty Hash > dist/checksum.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ext/${{github.ref_name}}-CHANGELOG
          files: |
            dist/idv-login-v10beta-${{github.ref_name}}.exe
            dist/checksum.txt