name: Build Beta

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ["3.8", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install pywin32 (Windows)
        if: runner.os == 'Windows'
        run: pip install pywin32

      # 插入构建信息（Windows）
      - name: Insert build info (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $buildInfo = 'BUILD_INFO="Build in ${{github.run_id}}(${{github.sha}})"'
          $versionInfo = 'VERSION="${{github.ref_name}}"'
          $buildInfo | Out-File -FilePath src/buildinfo.py -Encoding utf8
          $versionInfo | Out-File -FilePath src/buildinfo.py -Encoding utf8 -Append

      # 插入构建信息（macOS）
      - name: Insert build info (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo 'BUILD_INFO="Build in ${{github.run_id}}(${{github.sha}})"' > src/buildinfo.py
          echo 'VERSION="${{github.ref_name}}"' >> src/buildinfo.py

      - name: Build with PyInstaller
        run: |
          NAME="idv-login-${{github.ref_name}}-Py${{ matrix.python-version }}"
          if [ "${{ runner.os }}" = "macOS" ]; then
            NAME="${NAME}-mac"
          else
            NAME="${NAME}.exe"
          fi
          pyinstaller -F src/main.py -n "$NAME" -i assets/icon.ico --version-file assets/version.txt
        shell: bash


      # SHA256 校验（Windows）
      - name: Calculate checksum (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $file = "dist/idv-login-${{github.ref_name}}-Py${{ matrix.python-version }}.exe"
          Get-FileHash $file |
            Select-Object -ExpandProperty Hash |
            Out-File -Encoding ascii "$file.sha256"

      # SHA256 校验（macOS）
      - name: Calculate checksum (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          file="dist/idv-login-${{github.ref_name}}-Py${{ matrix.python-version }}-mac"
          shasum -a 256 "$file" | cut -d ' ' -f1 > "$file.sha256"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.python-version }}
          path: dist/

      - name: Release body
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ext/${{github.ref_name}}-CHANGELOG

  release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            **/*.exe
            **/*-mac
            **/*.sha256
