name: Build and Release

on:
  create:
    tags:
      - "auto-release-V[0-9]+.[0-9]"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install flask
          pip install requests
          pip install cryptography

      - name: Build with PyInstaller
        run: pyinstaller --onefile one-key.py -n one-key-${{github.ref_name}}.exe

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  build-win7:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install flask
          pip install requests
          pip install cryptography

      - name: Build with PyInstaller
        run: pyinstaller --onefile one-key.py -n one-key-${{github.ref_name}}-win7.exe

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-win7
          path: dist/

  release:
    needs: [build,build-win7]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Download win7 artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-win7

      - name: Install hashdeep
        run: |
          ls -R
          sudo apt-get install hashdeep

      - name: Compute checksum
        run: hashdeep -rlc sha256 *.exe > checksum-${{github.ref_name}}.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            one-key-${{github.ref_name}}.exe
            one-key-${{github.ref_name}}-win7.exe
            checksum-${{github.ref_name}}.txt
