name: Build and Release

on:
  push:
    branches:
      - one-key

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install flask
        pip install requests

    - name: Build with PyInstaller
      run: pyinstaller --onefile one-key.py 

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: Install hashdeep
      run: |
        ls -R
        sudo apt-get install hashdeep

    - name: Compute checksum
      run: hashdeep -rlc sha256 . > checksum.txt

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          one-key.exe
          checksum.txt