name: Update JSON Resources

on:
  push:
    paths:
      - 'assets/cloudRes.json'

jobs:
  sync_json:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://gitlab.com/KKeygen/idv-login.git'
            GIT_USERNAME: KKeygen
            GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}