name: Sync

on:
  push:
  workflow_dispatch:
jobs:
  sync-jihulab:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Mirror to JiHuLab
          uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://jihulab.com/KKeygenn/idv-login.git'
            GIT_USERNAME: KKeygenn
            GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}

  sync-gitee:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Mirror to Gitee
          uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://gitee.com/opguess/idv-login.git'
            GIT_USERNAME: opguess
            GIT_PASSWORD: ${{ secrets.GITEE_TOKEN }}