name: Sync

on:
  push:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://jihulab.com/KKeygenn/idv-login.git'
            GIT_USERNAME: KKeygenn
            GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}